### ISSUE TITLE
intheclear should run in the background when running

### ISSUE THREAD

**Issue by bxhghz** [SaferMobile/InTheClear#50] opened 2011-08-11 20:54 UTC
i activated In The Clear using the panic button, and see a dialogue box telling me that my sms and call logs are being deleted (This is right -- i selected these things).  It should hide this or I should have an option to hide this.  if I panicked because an antagonistic police person is taking my phone, I do not want that person to see that I am deleting info that they may want.  This might anger them and create a new risk to me.

**Comment by djhalliday** [comment] 2011-08-11 20:57
Currently the user experience is such that a dialog box appears showing a 5..4..3 countdown. This is correct.

Once the countdown reaches 0, however, the application should exit to the device home screen as activities are run in the background. No notifications should be shown, either. The ability to selectively configure notifications is a feature that will liklely make its way into milestone 0.4.

**Comment by djhalliday** [comment] 2011-08-11 21:12
closed, dupe of #50

**Closed as completed by djhalliday** 2011-08-11 21:12 UTC
Labels: SHOULD HAVE, ANDROID
