### ISSUE TITLE
cannot download/install ITC on nokia

### ISSUE THREAD

**Issue by bxhghz** [SaferMobile/InTheClear#79] opened 2011-09-07 22:55 UTC
i'm using a nokia 2700, trying to install ITC and when I visit safermobile.org/intheclear and follow the install java link, i am led to a single file, "intheclear.jad" -- when I click on this, i get  a message that says "invalid web settings."  i expected to be led to an install file.  

is this a device setting issue or something with the java download.

B

**Comment by n8fr8** [comment] 2011-09-08 01:28
## Mobile network config issue. You need the right tmobile settings for gprs/wap.

Sent from my Guardian-powered Android phone with K-9 Mail. Please excuse my brevity.

Becky Hurwitz reply@reply.github.com wrote:

i'm using a nokia 2700, trying to install ITC and when I visit safermobile.org/intheclear and follow the install java link, i am led to a single file, "intheclear.jad" -- when I click on this, i get a message that says "invalid web settings." i expected to be led to an install file. 

is this a device setting issue or something with the java download.

B

## 

Reply to this email directly or view it on GitHub:
https://github.com/SaferMobile/InTheClear/issues/79

**Comment by n8fr8** [comment] 2011-10-07 21:48
Closing this ticket, because the issue is the phone does not have internet setup properly. Nothing we can fix.

**Closed as completed by n8fr8** 2011-10-07 21:48 UTC
Labels: J2ME
